### ISSUE TITLE
good code

### ISSUE THREAD

**Issue by lixy123** [atomic14/esp32_deep_sleep#1]
Your area of concern is very similar to mine. 
Welcome to visit my website https://github.com/lixy123

The code of esp32 deep sleep is very instructive.
if using "DEEP_SLEEP_EXT0" mode:
1.If battery powered, Avoid as much as possible using "rtc_gpio_hold_en" Because it will consume 1-2mA more current,
The use of current is very precious.
2.call "gpio_hold_dis, gpio_deep_sleep_hold_dis" after wake up,  Otherwise, the GPIO is still in the last state after waking up

**Comment by cgreening** [comment]
Thanks for the tips!
